import sqlite3, json, time, uuid, os
from pathlib import Path
from contextlib import contextmanager
import re
import psycopg
from psycopg import sql
from backend.connections import tls_options
from backend import monitoring

DB = Path(os.environ.get("JOB_STORE", ".data/jobs.sqlite3"))


_waker = None


class ActiveJob(Exception):
    pass


class Record(dict):
    def __getitem__(self, key):
        return (
            list(self.values())[key]
            if isinstance(key, int)
            else super().__getitem__(key)
        )


def record_factory(cursor):
    columns = [c.name for c in cursor.description or []]
    return lambda values: Record(zip(columns, values))


def postgres():
    return bool(os.environ.get("JOB_DATABASE_URL"))


def schema():
    name = os.environ.get("JOB_DATABASE_SCHEMA", "qot_app")
    if not re.fullmatch(r"[a-z_][a-z0-9_]{0,62}", name):
        raise ValueError("Invalid job-store schema")
    return name


class PostgresConnection:
    """Only internal static SQL uses this qmark interface."""

    def __init__(self):
        self.raw = psycopg.connect(
            os.environ["JOB_DATABASE_URL"],
            connect_timeout=10,
            row_factory=record_factory,
            options=f"-c search_path={schema()},pg_catalog -c statement_timeout=15000 -c lock_timeout=3000",
            **tls_options(os.environ["JOB_DATABASE_URL"]),
        )

    def execute(self, query, params=None):
        return self.raw.execute(query.replace("?", "%s"), params)

    def __enter__(self):
        self.raw.__enter__()
        return self

    def __exit__(self, *args):
        return self.raw.__exit__(*args)


def set_waker(callback):
    global _waker
    _waker = callback


class SQLiteConnection(sqlite3.Connection):
    def __exit__(self, *args):
        try:
            return super().__exit__(*args)
        finally:
            self.close()


def connect():
    if postgres():
        return PostgresConnection()
    DB.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB, timeout=10, factory=SQLiteConnection)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def init():
    if postgres():
        with connect() as c:
            c.raw.execute(
                sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                    sql.Identifier(schema())
                )
            )
            for statement in [
                "CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, owner TEXT NOT NULL, request_key TEXT NOT NULL, case_id TEXT, query TEXT, state TEXT NOT NULL, created DOUBLE PRECISION NOT NULL, updated DOUBLE PRECISION NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, cancel INTEGER NOT NULL DEFAULT 0, report TEXT, error TEXT, UNIQUE(owner,request_key))",
                "CREATE TABLE IF NOT EXISTS events(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job TEXT NOT NULL REFERENCES jobs(id), stage TEXT, message TEXT, at DOUBLE PRECISION)",
                "CREATE TABLE IF NOT EXISTS connections(id TEXT PRIMARY KEY, owner TEXT NOT NULL, label TEXT NOT NULL, secret TEXT NOT NULL)",
                "CREATE TABLE IF NOT EXISTS limits(bucket TEXT PRIMARY KEY, n INTEGER NOT NULL, reset DOUBLE PRECISION NOT NULL)",
                "CREATE INDEX IF NOT EXISTS jobs_owner_created ON jobs(owner,created DESC)",
                "CREATE INDEX IF NOT EXISTS jobs_queue ON jobs(created,id) WHERE state='queued' AND cancel=0",
                "CREATE INDEX IF NOT EXISTS events_job_id ON events(job,id)",
                "CREATE UNIQUE INDEX IF NOT EXISTS jobs_one_active_owner ON jobs(owner) WHERE state IN ('queued','running')",
            ]:
                c.execute(statement)
            c.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS trace_context TEXT")
        return
    with connect() as c:
        c.executescript("""CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, owner TEXT NOT NULL, request_key TEXT NOT NULL, case_id TEXT, query TEXT, state TEXT NOT NULL, created REAL NOT NULL, updated REAL NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, cancel INTEGER NOT NULL DEFAULT 0, report TEXT, error TEXT, UNIQUE(owner,request_key));
        CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT, job TEXT NOT NULL, stage TEXT, message TEXT, at REAL);
        CREATE TABLE IF NOT EXISTS connections(id TEXT PRIMARY KEY, owner TEXT NOT NULL, label TEXT NOT NULL, secret TEXT NOT NULL);
        CREATE TABLE IF NOT EXISTS limits(bucket TEXT PRIMARY KEY, n INTEGER NOT NULL, reset REAL NOT NULL);""")
        if "trace_context" not in {row[1] for row in c.execute("PRAGMA table_info(jobs)")}:
            c.execute("ALTER TABLE jobs ADD COLUMN trace_context TEXT")


def job(row):
    if not row:
        return None
    d = dict(row)
    d["report"] = json.loads(d["report"]) if d["report"] else None
    with connect() as c:
        d["events"] = [
            dict(x)
            for x in c.execute(
                "SELECT stage,message,at FROM events WHERE job=? ORDER BY id",
                (d["id"],),
            )
        ]
    d.pop("request_key", None)
    d.pop("owner", None)
    d.pop("trace_context", None)
    return d


def get(id, owner):
    with connect() as c:
        row = c.execute(
            "SELECT * FROM jobs WHERE id=? AND owner=?", (id, owner)
        ).fetchone()
    return job(row)


def create(owner, key, case_id, query):
    try:
        with connect() as c:
            c.execute(
                "INSERT INTO jobs(id,owner,request_key,case_id,query,state,created,updated,trace_context) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(owner,request_key) DO NOTHING",
                (
                    uuid.uuid4().hex,
                    owner,
                    key,
                    case_id,
                    query,
                    "queued",
                    time.time(),
                    time.time(),
                    json.dumps(monitoring.queued_trace()),
                ),
            )
            row = c.execute(
                "SELECT * FROM jobs WHERE owner=? AND request_key=?", (owner, key)
            ).fetchone()
    except (sqlite3.IntegrityError, psycopg.errors.UniqueViolation):
        raise ActiveJob() from None
    # Notify only after commit, so the worker can see the job.
    if _waker:
        _waker()
    return job(row)


def event(id, stage, message):
    with connect() as c:
        c.execute(
            "INSERT INTO events(job,stage,message,at) VALUES(?,?,?,?)",
            (id, stage, message, time.time()),
        )
        c.execute("UPDATE jobs SET updated=? WHERE id=?", (time.time(), id))


def finish(id, state, report=None, error=None):
    with connect() as c:
        c.execute(
            "UPDATE jobs SET state=?,report=?,error=?,updated=? WHERE id=?",
            (
                state,
                json.dumps(report, default=str) if report else None,
                error,
                time.time(),
                id,
            ),
        )


def claim():
    with connect() as c:
        if postgres():
            row = c.execute(
                "UPDATE jobs SET state='running',attempts=attempts+1,updated=? WHERE id=(SELECT id FROM jobs WHERE state='queued' AND cancel=0 ORDER BY created,id LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING *",
                (time.time(),),
            ).fetchone()
            return dict(row) if row else None
        c.execute("BEGIN IMMEDIATE")
        row = c.execute(
            "SELECT * FROM jobs WHERE state='queued' AND cancel=0 ORDER BY created LIMIT 1"
        ).fetchone()
        if row:
            c.execute(
                "UPDATE jobs SET state='running',attempts=attempts+1,updated=? WHERE id=?",
                (time.time(), row["id"]),
            )
        return dict(row) if row else None


def limit(bucket, maximum, window):
    now = time.time()
    if maximum <= 0:
        return False
    with connect() as c:
        if postgres():
            row = c.execute(
                "INSERT INTO limits(bucket,n,reset) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET n=CASE WHEN limits.reset<=? THEN 1 ELSE limits.n+1 END, reset=CASE WHEN limits.reset<=? THEN excluded.reset ELSE limits.reset END WHERE limits.reset<=? OR limits.n<? RETURNING bucket",
                (bucket, now + window, now, now, now, maximum),
            ).fetchone()
            return row is not None
        c.execute("BEGIN IMMEDIATE")
        row = c.execute(
            "SELECT n,reset FROM limits WHERE bucket=?", (bucket,)
        ).fetchone()
        if row and row["reset"] > now and row["n"] >= maximum:
            return False
        if not row or row["reset"] <= now:
            c.execute(
                "INSERT OR REPLACE INTO limits VALUES(?,1,?)", (bucket, now + window)
            )
        else:
            c.execute("UPDATE limits SET n=n+1 WHERE bucket=?", (bucket,))
        return True


def recover():
    with connect() as c:
        c.execute(
            "UPDATE jobs SET state='queued',updated=? WHERE state='running' AND attempts<2 AND cancel=0",
            (time.time(),),
        )
        c.execute(
            "UPDATE jobs SET state='failed',error='Worker interrupted; retry budget exhausted.' WHERE state='running' AND cancel=0"
        )
        c.execute(
            "UPDATE jobs SET state='cancelled' WHERE cancel=1 AND state IN ('queued','running')"
        )


@contextmanager
def worker_lock():
    """Single ownership across overlapping Railway deployments."""
    if postgres():
        with psycopg.connect(
            os.environ["JOB_DATABASE_URL"],
            autocommit=True,
            connect_timeout=10,
            **tls_options(os.environ["JOB_DATABASE_URL"]),
        ) as c:
            if not c.execute("SELECT pg_try_advisory_lock(1364157527)").fetchone()[0]:
                raise BlockingIOError("Another worker owns this store")
            yield c
        return
    DB.parent.mkdir(parents=True, exist_ok=True)
    with (DB.parent / "worker.lock").open("a+b") as lock:
        if os.name == "nt":
            import msvcrt

            lock.write(b"0")
            lock.flush()
            lock.seek(0)
            msvcrt.locking(lock.fileno(), msvcrt.LK_NBLCK, 1)
        else:
            import fcntl

            fcntl.flock(lock.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        yield None
